### ISSUE TITLE
Add Multiple Level to each Categories

### ISSUE THREAD

**Issue by AnishAzharudeen** [SonaliP11/Little-Genius-Academy#61]
**User Story:**

- [ ] As a kid, I want to view the difficulty level (easy, medium, hard) so that I can choose a quiz that matches my skill level.

**Acceptance Criteria:**

- [ ] The quiz selection page displays difficulty level options.
- [ ] Selecting a difficulty level should load questions appropriate to the chosen level

**Tasks**

- [ ] Frontend Development: Design a level selection menu with options for "Easy," "Medium," and "Hard," displayed before starting the quiz.
- [ ] Backend Logic: Configure the quiz API to filter and retrieve questions based on the selected difficulty level.

**Comment by AnishAzharudeen** [comment]
I have added Level... 
Shari needs to add Styling to it

**Comment by sharichungcode** [comment]
Might not be included in the MVP, but can add review mode for parents/teachers when have time.
