### ISSUE TITLE
Save Name in URL

### ISSUE THREAD

**Issue by AnishAzharudeen** [SonaliP11/Little-Genius-Academy#69]
**User Story**
As a child user, I want my name to be saved in the URL so that I can easily return to the quiz later without having to re-enter my name.

**Acceptance Criteria**

- [x] When the user enters their name, the name should be appended to the URL as a query parameter (e.g., ?name=John).
- [x] Upon returning to the quiz page, the system should automatically pre-fill the name field with the name from the URL if it exists.

**Tasks**

- [x] Frontend Development: Modify the quiz page to capture the user's name from the input field and append it as a query parameter in the URL.
- [x] URL Parsing: Implement logic to detect the name in the URL on page load and pre-fill the name field if the name is available in the URL.

**Comment by SonaliP11** [comment]
****
