### ISSUE TITLE
Quiz Feature for Kids

### ISSUE THREAD

**Issue by SonaliP11** [SonaliP11/Little-Genius-Academy#83]
**User Story**

- [x] As a child user, I want to take quizzes on the Little Genius Academy website so that I can test my knowledge and learn new things in a fun way.

**Acceptance Criteria:**

- [x]  The quiz should display one question at a time with multiple-choice answers.

- [ ]  An answer selected should be highlighted and feedback is there (correct/incorrect) and proceed to the next question.

**Tasks:**

- [x] Frontend Development: Create a responsive quiz interface with a question, four answer options.

- [x]  Backend Development: Set up an API to retrieve quiz questions and answers from a database.
